import assert from 'node:assert/strict';
const base='http://127.0.0.1:3210';
async function api(route,data){const res=await fetch(base+route,data?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}:{});const result=await res.json();assert.equal(res.status,200,JSON.stringify(result));return result;}
async function wait(value){if(!value.job)return value;for(;;){const state=await api('/api/job?id='+value.job);if(state.status==='done')return state.result;if(state.status==='error')throw Error(state.error);await new Promise(r=>setTimeout(r,1500));}}
const session=await api('/api/session',{challenge:'cache'});
const interview=await api('/api/interview/start',{id:session.id});assert.equal(interview.deadline-interview.started,45*60*1000);console.log('Started 45-minute interview:',interview.id);
const reply=await wait(await api('/api/interview/turn',{id:session.id,path:'cache.mjs',kind:'answer',text:'I would inject a fake clock to test an entry just before, exactly at, and after its expiration. I suspect the comparison uses the clock function instead of calling it. I also want to test zero and false so missing values are not confused with falsy values.'}));assert.equal(reply.transcript.length,3);console.log('Interviewer response:',reply.transcript.at(-1).content);
const hint=await wait(await api('/api/interview/turn',{id:session.id,path:'cache.mjs',kind:'hint'}));assert.equal(hint.hints,1);console.log('Hint recorded.');
const feature=await wait(await api('/api/interview/turn',{id:session.id,path:'cache.mjs',kind:'feature'}));assert.ok(feature.feature?.length>30);console.log('Feature assignment:',feature.feature);
const ended=await wait(await api('/api/interview/end',{id:session.id,path:'cache.mjs',reason:'give_up'}));assert.equal(ended.status,'ended');assert.equal(ended.report.rubric.length,5);console.log('Feedback generated by:',ended.report.generatedBy);console.log(ended.report.summary);if(ended.report.generationError)throw Error(ended.report.generationError);
await api('/api/interview/practice',{id:session.id});console.log('Returned to free practice; report retained.');
